let songs = [
  {
    title: 'Like Ooh-Ahh',
    artist: 'TWICE',
    cover: 'cover/1.jpg',
    path: 'audio/Like Ooh-Ahh.mp3',
  },
  {
    title: 'CHEER UP',
    artist: 'TWICE',
    cover: 'cover/2.jpg',
    path: 'audio/CHEER UP.mp3',
  },
  {
    title: 'TT',
    artist: 'TWICE',
    cover: 'cover/3.jpg',
    path: 'audio/TT.mp3',
  },
  {
    title: 'Knock Knock',
    artist: 'TWICE',
    cover: 'cover/4.jpg',
    path: 'audio/Knock Knock.mp3',
  },
  {
    title: 'Signal',
    artist: 'TWICE',
    cover: 'cover/5.jpg',
    path: 'audio/Signal.mp3',
  },
  {
    title: 'Likely',
    artist: 'TWICE',
    cover: 'cover/6.jpg',
    path: 'audio/Likely.mp3',
  },
  {
    title: 'Heart Shaker',
    artist: 'TWICE',
    cover: 'cover/7.jpg',
    path: 'audio/Heart Shaker.mp3',
  },
  {
    title: 'What is Love',
    artist: 'TWICE',
    cover: 'cover/8.jpg',
    path: 'audio/What is Love.mp3',
  },
  {
    title: 'Dance the Night Away',
    artist: 'TWICE',
    cover: 'cover/9.jpg',
    path: 'audio/Dance the Night Away.mp3',
  },
  {
    title: 'Yes or Yes',
    artist: 'TWICE',
    cover: 'cover/10.jpg',
    path: 'audio/Yes or Yes.mp3',
  },
  {
    title: 'The Best Thing I Ever Did',
    artist: 'TWICE',
    cover: 'cover/11.jpg',
    path: 'audio/The Best Thing I Ever Did.mp3',
  },
  {
    title: 'FANCY',
    artist: 'TWICE',
    cover: 'cover/12.jpg',
    path: 'audio/FANCY.mp3',
  },
  {
    title: 'Feel Special',
    artist: 'TWICE',
    cover: 'cover/13.jpg',
    path: 'audio/Feel Special.mp3',
  },
  {
    title: 'MORE & MORE',
    artist: 'TWICE',
    cover: 'cover/14.jpg',
    path: 'audio/MORE & MORE.mp3',
  },
  {
    title: 'CRY FOR ME',
    artist: 'TWICE',
    cover: 'cover/15.jpg',
    path: 'audio/CRY FOR ME.mp3',
  },
  {
    title: 'I CAN\'T STOP ME',
    artist: 'TWICE',
    cover: 'cover/16.jpg',
    path: 'audio/I CANT STOP ME.mp3',
  },
  {
    title: 'Alcohol-Free',
    artist: 'TWICE',
    cover: 'cover/17.jpg',
    path: 'audio/AlcoholFree.mp3',
  },
  {
    title: 'The Feels',
    artist: 'TWICE',
    cover: 'cover/18.jpg',
    path: 'audio/The Feels.mp3',
  },
  {
    title: 'SCIENTIST',
    artist: 'TWICE',
    cover: 'cover/19.jpg',
    path: 'audio/SCIENTIST.mp3',
  },
  {
    title: 'Talk that Talk',
    artist: 'TWICE',
    cover: 'cover/20.jpg',
    path: 'audio/Talk that Talk.mp3',
  },
  {
    title: 'MOONLIGHT SUNRISE',
    artist: 'TWICE',
    cover: 'cover/21.jpg',
    path: 'audio/MOONLIGHT SUNRISE.mp3',
  },
  {
    title: 'SET ME FREE',
    artist: 'TWICE',
    cover: 'cover/22.jpg',
    path: 'audio/SET ME FREE.mp3',
  },
  {
    title: 'I GOT YOU',
    artist: 'TWICE',
    cover: 'cover/23.jpg',
    path: 'audio/I GOT YOU.mp3',
  },
  {
    title: 'ONE SPARK',
    artist: 'TWICE',
    cover: 'cover/24.jpg',
    path: 'audio/ONE SPARK.mp3',
  },
];

